using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using Photon.Realtime;

public class GameManager : MonoBehaviour
{
    public static GameManager instance = null;
    public bool isConnect = false;
    public Transform[] spawnPoints;

    private void Awake()
    {
       if(instance==null)
        {
            instance = this;
            DontDestroyOnLoad(this.gameObject);
        }
       else if(instance !=this)
        {
            Destroy(this.gameObject);
        }
    }

    void Start()
    {
       //StartCoroutine(CreatePlayer());
    } 

     void Update()
    {
        
    }

    IEnumerator CreatePlayer()
    {
        yield return new WaitUntil(() => isConnect);

        spawnPoints = GameObject.Find("SpawnPointGroup").GetComponentsInChildren<Transform>();

        Vector3 pos = spawnPoints[PhotonNetwork.CurrentRoom.PlayerCount].position;
        Quaternion rot = spawnPoints[PhotonNetwork.CurrentRoom.PlayerCount].rotation;
        
        GameObject playerTemp = PhotonNetwork.Instantiate("PlayerArmature", Vector3.one, Quaternion.identity, 0);
    }
}
